name: goldscreencinema

services:
  frontend:
    build:
      context: ./frontend
    restart: unless-stopped
    networks:
      - gsc_internal
    depends_on:
      - api
    ports:
      - "80:80"
      - "443:443"
    
  api:
    container_name: api
    build:
      context: ./api
    restart: unless-stopped
    networks:
      - gsc_internal
    ports:
      - "4000:4000"

networks:
  gsc_internal:
    driver: bridge
    