name: GSC ci-cd pipeline

on:
  push:
    branches:
      - main

jobs:
  Testing:
    name: Testing the frontend
    runs-on: ubuntu-latest
    container:
      image: node:23-alpine3.19
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Install the dependcies
        run: |
          cd frontend
          npm ci
      - name: Install the dependcies
        run: |
          cd frontend
          npm run test  
