name: GSC ci-cd pipeline

on:
  push:
    branches:
      - main

jobs:
  say-hello:
    name: Say hello world
    runs-on: ubuntu-latest
    container:
      image: node:23-alpine3.19
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: echo hello world
        uses: echo "Hello world"    
